# Generated by Django 4.1.1 on 2023-01-12 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailsendingfact",
            options={
                "verbose_name": "Имейл заказа фотографий",
                "verbose_name_plural": "Имейлы заказов фотографий",
            },
        ),
        migrations.AlterModelOptions(
            name="emailtype",
            options={
                "verbose_name": "Тип имейла",
                "verbose_name_plural": "Типы имейлов",
            },
        ),
    ]
