# Generated by Django 4.1.1 on 2023-03-08 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0014_alter_cartmodel_product_count"),
        ("emails", "0002_alter_emailsendingfact_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSendingFactProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.shopordermodel",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="emails.emailtype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Имейл заказа в магазине",
                "verbose_name_plural": "Имейлы заказов в магазине",
            },
        ),
    ]
