# Generated by Django 4.1.1 on 2022-12-11 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="papiertype",
            options={
                "verbose_name": "Тип бумаги",
                "verbose_name_plural": "Типы бумаги",
            },
        ),
        migrations.RemoveField(
            model_name="papiertype",
            name="papier_height",
        ),
        migrations.RemoveField(
            model_name="papiertype",
            name="papier_width",
        ),
        migrations.CreateModel(
            name="PapierSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "papier_width",
                    models.PositiveIntegerField(
                        blank=True, unique=True, verbose_name="Ширина"
                    ),
                ),
                (
                    "papier_height",
                    models.PositiveIntegerField(
                        blank=True, unique=True, verbose_name="Высота"
                    ),
                ),
                (
                    "papier_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="print.papiertype",
                        verbose_name="Тип бумаги",
                    ),
                ),
            ],
            options={
                "verbose_name": "Размер фотографии",
                "verbose_name_plural": "Размеры фоторафий",
            },
        ),
    ]
