# Generated by Django 4.1.1 on 2022-12-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0002_alter_papiertype_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="papiersize",
            name="papier_height",
            field=models.PositiveIntegerField(blank=True, verbose_name="Высота"),
        ),
        migrations.AlterField(
            model_name="papiersize",
            name="papier_width",
            field=models.PositiveIntegerField(blank=True, verbose_name="Ширина"),
        ),
    ]
