# Generated by Django 4.1.1 on 2022-12-11 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0003_alter_papiersize_papier_height_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="services",
            name="papier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="print.papiersize",
                verbose_name="Тип бумаги",
            ),
        ),
    ]
