# Generated by Django 4.1.1 on 2022-12-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0004_alter_services_papier"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("10x15", "10x15"),
                            ("15x21", "15x21"),
                            ("20x30", "20x30"),
                        ],
                        default="10x15",
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотографии заказа",
                "verbose_name_plural": "Фотографии заказов",
            },
        ),
    ]
