# Generated by Django 4.1.1 on 2022-12-12 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0005_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="services",
            name="papier",
        ),
        migrations.AddField(
            model_name="services",
            name="papier_size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="print.papiersize",
                verbose_name="Размер фотографии",
            ),
        ),
        migrations.AddField(
            model_name="services",
            name="papier_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="print.papiertype",
                verbose_name="Тип бумаги",
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="format",
            field=models.CharField(
                blank=True, choices=[], default="10x15", max_length=50
            ),
        ),
    ]
