# Generated by Django 4.1.1 on 2022-12-12 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0006_remove_services_papier_services_papier_size_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="papiersize",
            name="papier_type",
        ),
    ]
