# Generated by Django 4.1.1 on 2022-12-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0007_remove_papiersize_papier_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("Матовая", "Матовая"), ("Глянцевая", "Глянцевая")],
                default="Глянцевая",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="format",
            field=models.CharField(
                blank=True,
                choices=[("10x15", "10x15"), ("15x21", "15x21"), ("20x30", "20x30")],
                default="10x15",
                max_length=50,
            ),
        ),
    ]
