# Generated by Django 4.1.1 on 2022-12-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0008_photo_type_alter_photo_format"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="type",
            new_name="papier",
        ),
    ]
