# Generated by Django 4.1.1 on 2022-12-12 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import print.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("print", "0009_rename_type_photo_papier"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="count",
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name="photo",
            name="file",
            field=models.ImageField(
                null=True, upload_to=print.utils.user_directory_path
            ),
        ),
        migrations.AddField(
            model_name="photo",
            name="session_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="uploaded_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="photo",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
