# Generated by Django 4.1.1 on 2022-12-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0010_photo_count_photo_file_photo_session_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="format",
            field=models.CharField(
                choices=[("10x15", "10x15"), ("15x21", "15x21"), ("20x30", "20x30")],
                default="10x15",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="papier",
            field=models.CharField(
                choices=[("Матовая", "Матовая"), ("Глянцевая", "Глянцевая")],
                default="Глянцевая",
                max_length=50,
            ),
        ),
    ]
