# Generated by Django 4.1.1 on 2023-01-02 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("print", "0011_alter_photo_format_alter_photo_papier"),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        verbose_name="Имя заказчика",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        verbose_name="Фамилия заказчика",
                    ),
                ),
                (
                    "delivery",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Способ доставки",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Адрес доставки",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Комментарии к заказу",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время заказа"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "link",
                    models.FilePathField(
                        allow_folders=True,
                        blank=True,
                        null=True,
                        verbose_name="Папка с заказом",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Сформированный заказ",
                "verbose_name_plural": "Сформированные заказы",
            },
        ),
        migrations.CreateModel(
            name="OrderPhotos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="")),
                ("text_file", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="print.orders",
                    ),
                ),
            ],
        ),
    ]
