# Generated by Django 4.1.1 on 2023-01-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0013_orders_email_orders_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderphotos",
            old_name="text_file",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="orderphotos",
            name="image",
        ),
        migrations.AddField(
            model_name="orderphotos",
            name="count",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="orderphotos",
            name="price",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
