# Generated by Django 4.1.1 on 2023-01-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0014_rename_text_file_orderphotos_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="session_key",
        ),
        migrations.AddField(
            model_name="orders",
            name="file_field",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
