# Generated by Django 4.1.1 on 2022-12-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MainCardModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="site-images", verbose_name="Изображение"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Название"
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=150, verbose_name="Описание"),
                ),
                (
                    "description_uk",
                    models.TextField(
                        max_length=150, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        max_length=150, null=True, verbose_name="Описание"
                    ),
                ),
                ("post_link", models.URLField()),
            ],
            options={
                "verbose_name": "Карточка на главной странице",
                "verbose_name_plural": "Карточки на главной странице",
            },
        ),
    ]
