# Generated by Django 4.0 on 2023-04-16 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_flatpagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincardmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='flatpagemodel',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
