# Generated by Django 4.0 on 2023-04-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_flatpagemodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpagemodel',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='flatpagemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site-images', verbose_name='Изображение'),
        ),
    ]
