# Generated by Django 4.0 on 2023-04-16 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_flatpagemodel_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название страницы')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, verbose_name='URL')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Телефон')),
                ('work_time', models.CharField(blank=True, max_length=150, null=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Страница контакты',
            },
        ),
    ]
