# Generated by Django 4.0 on 2023-04-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_contactpagemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactpagemodel',
            options={'verbose_name': 'Страница контакты', 'verbose_name_plural': 'Страница контакты'},
        ),
        migrations.RenameField(
            model_name='contactpagemodel',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='contactpagemodel',
            name='address',
            field=models.TextField(blank=True, max_length=250, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='contactpagemodel',
            name='work_time',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Время работы'),
        ),
    ]
