# Generated by Django 4.0 on 2023-04-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_contactpagemodel_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSliderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='site-images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Слайды',
                'verbose_name_plural': 'Слайдер на главной странице',
            },
        ),
    ]
