# Generated by Django 4.0 on 2023-04-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_mainslidermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainslidermodel',
            name='post_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка'),
        ),
    ]
