# Generated by Django 4.1.1 on 2023-01-24 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="shop.productcategorymodel",
                verbose_name="Категория товара",
            ),
            preserve_default=False,
        ),
    ]
