# Generated by Django 4.1.1 on 2023-01-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0002_productmodel_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="photos",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
