# Generated by Django 4.1.1 on 2023-01-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0003_productmodel_photos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="photos",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
