# Generated by Django 4.1.1 on 2023-01-25 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0005_remove_productmodel_photos"),
    ]

    operations = [
        migrations.AddField(
            model_name="productphoto",
            name="for_category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_category_images",
                to="shop.productcategorymodel",
            ),
            preserve_default=False,
        ),
    ]
