# Generated by Django 4.1.1 on 2023-02-24 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import json.decoder
import json.encoder


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0007_alter_productphoto_for_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="rating",
            field=models.FloatField(blank=True, null=True, verbose_name="Рейтинг"),
        ),
        migrations.CreateModel(
            name="ShopOrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        verbose_name="Имя заказчика",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        verbose_name="Фамилия заказчика",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "delivery",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Способ доставки",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Адрес доставки",
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Комментарии к заказу",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время заказа"
                    ),
                ),
                (
                    "link",
                    models.JSONField(
                        blank=True,
                        decoder=json.decoder.JSONDecoder,
                        encoder=json.encoder.JSONEncoder,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ в магазине",
                "verbose_name_plural": "Заказы в магазине",
            },
        ),
        migrations.CreateModel(
            name="CartModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_count",
                    models.PositiveIntegerField(blank=True, default=1, null=True),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.productmodel",
                        verbose_name="Товар в корзине",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Корзина товаров",
                "verbose_name_plural": "Корзины товаров",
            },
        ),
    ]
