# Generated by Django 4.1.1 on 2023-02-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0011_productmodel_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="sizes",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Размеры"
            ),
        ),
    ]
