# Generated by Django 4.1.1 on 2023-02-28 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0012_productmodel_sizes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartmodel",
            options={
                "verbose_name": "Корзина заказа",
                "verbose_name_plural": "Корзины заказов",
            },
        ),
        migrations.RemoveField(
            model_name="productmodel",
            name="category_name",
        ),
    ]
