# Generated by Django 4.0 on 2023-05-05 06:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_productreviewsmodel_moderated'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreviewsmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата и время отзыва'),
            preserve_default=False,
        ),
    ]
