# Generated by Django 4.1.1 on 2023-07-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0018_alter_productreviewsmodel_moderated_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productreviewsmodel",
            name="avatar",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
