# Generated by Django 4.0 on 2023-09-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_productreviewsmodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreviewsmodel',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
