# Generated by Django 4.0 on 2023-09-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_productreviewsmodel_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreviewsmodel',
            name='avatar',
        ),
    ]
