# Generated by Django 4.1.1 on 2023-01-18 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Категория фотографии",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория в портфолио",
                "verbose_name_plural": "Категории в портфолио",
            },
        ),
        migrations.CreateModel(
            name="PortfolioPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(upload_to="portfolio", verbose_name="Фотография"),
                ),
                (
                    "photo_desc",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Описание фотографии",
                    ),
                ),
                (
                    "active",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="portfolio.portfolio",
                    ),
                ),
            ],
        ),
    ]
