# Generated by Django 4.1.1 on 2023-01-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="portfolio",
            options={
                "verbose_name": "Фотография в портфолио",
                "verbose_name_plural": "Фотографии в портфолио",
            },
        ),
        migrations.RenameField(
            model_name="portfoliophoto",
            old_name="photo",
            new_name="src",
        ),
    ]
