# Generated by Django 4.1.1 on 2023-01-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_alter_portfolio_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfoliophoto",
            name="height",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="portfoliophoto",
            name="width",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
