# Generated by Django 4.1.1 on 2023-01-21 07:59

from django.db import migrations, models

def add_translation(apps, schema_editor):
    Author = apps.get_model('app_name', 'Author')
    Language = apps.get_model('app_name', 'Language')
    Book = apps.get_model('app_name', 'Book')

    # Получаем авторов Аркадий Стругацкий и Борис Стругацкий
    strugatsky_authors = Author.objects.filter(last_name__in=['Стругацкий Аркадий', 'Стругацкий Борис'])

    # Получаем язык Суахили
    suahili = Language.objects.get(name='Суахили')

    # Получаем книги авторов Аркадий Стругацкий и Борис Стругацкий
    strugatsky_books = Book.objects.filter(authors__in=strugatsky_authors)

    # Добавляем язык Суахили в список языков, на которые переведены книги
    for book in strugatsky_books:
        book.available_languages.add(suahili)
    


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_portfoliophoto_height_portfoliophoto_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfoliophoto",
            name="height",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portfoliophoto",
            name="width",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
