# Generated by Django 4.1.1 on 2023-01-21 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_portfoliophoto_height_portfoliophoto_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfoliophoto",
            name="height",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="portfoliophoto",
            name="width",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
