# Generated by Django 4.1.1 on 2022-12-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="email",
            field=models.EmailField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="phone",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
