# Generated by Django 4.1.1 on 2022-12-10 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_usermodel_city_alter_usermodel_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="phone",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
