# Generated by Django 4.1.1 on 2022-12-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_usermodel_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="phone",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
