# Generated by Django 4.1.1 on 2022-12-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_usermodel_avatar_alter_usermodel_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="city",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Адрес доставки"
            ),
        ),
    ]
