# Generated by Django 4.1.1 on 2023-01-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_alter_usermodel_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="city",
            field=models.TextField(
                blank=True, max_length=100, verbose_name="Адрес доставки"
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="first_name",
            field=models.CharField(blank=True, max_length=64, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="last_name",
            field=models.CharField(blank=True, max_length=64, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="phone",
            field=models.CharField(blank=True, max_length=13, verbose_name="Телефон"),
        ),
    ]
